remote: true

experienceLevel:
 internship: false
 entry: false
 associate: false
 mid-senior level: true
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: false
 part-time: false
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: false
 month: false
 week: false
 24 hours: true

positions:
  - Senior Software Engineer
  - Senior Backend Engineer
  - Senior Software Developer

locations:
  - United States

distance: 1000

companyBlacklist:

titleBlacklist:
  - Fullstack
  - Full-stack
  - Full Stack
  - Frontend
  - Front-end
  - Front End
  - Test
  - DevOps